FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Hello World API

## Hello World [/]

### Get a Hello World [GET]

+ Response 200 (application/json; charset=utf-8)

        {"message": "Hello World!"}
